name: Daily Job Search

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-job-search:
    runs-on: ubuntu-latest
    env:
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas

      - name: Run job search script
        run: |
          python job_search_email_agent_logged.py | tee script_output.log

